### ISSUE TITLE
Charter update

### ISSUE THREAD

**Issue by hober** [privacycg/admin#13]
We published an [updated charter](https://privacycg.github.io/charter.html) today which contains a number of improvements.

* Formalizes the role of Proposal Champion, which is similar to in TC39.
* Modify the rules for how Work Items get adopted, modified, and removed.
* Drop our bespoke definition of "implementer," since the rules for adding/modifying/removing Work Items no longer depend on it.

This change was landed in commit [3b2018d](https://github.com/privacycg/privacycg.github.io/commit/3b2018d2550e13f64fbfd69a4a834058b534f81c) by merging PR privacycg/privacycg.github.io#26.

As with all announcements, we'll talk about this on our next telcon, and will leave this notice up for at least a week.

**Comment by cwilso** [comment]
Thanks so much for all the long work on this, @hober!  Looking forward to joining the CG.
