### ISSUE TITLE
Teleconference meeting information is wrong?

### ISSUE THREAD

**Issue by djnym** [privacycg/admin#19]
I just joined the group yesterday, and feel that I may have missed a call this morning.

Which is confusing because the only information I found on when calls take place is in the meetings README https://github.com/privacycg/meetings/blob/master/2020/telcons/README.md
Which states "The Privacy CG meets on the 2nd and 4th Thursdays of each month, at noon Boston time (EDT)."

However, I started looking back at mailing list archives and there is a suggestion that there was a call today
https://lists.w3.org/Archives/Public/public-privacy/2020OctDec/0027.html
but that email doesn't actually contain any call information, so if I had seen it, would I have used the call information in the README (which suggests the zoom link is https://mozilla.zoom.us/j/769153986)

So my question is, if I want to participate in the calls, when are they, and where is the most up to date information about them.

Thanks,
-Anthony

**Comment by hober** [comment]
> I just joined the group yesterday, and feel that I may have missed a call this morning.

You didn't.

> Which is confusing because the only information I found on when calls take place is in the meetings README https://github.com/privacycg/meetings/blob/master/2020/telcons/README.md
> Which states "The Privacy CG meets on the 2nd and 4th Thursdays of each month, at noon Boston time (EDT)."

This information is correct (except that Boston is now on EST. I'll go fix that, thanks!)

> So my question is, if I want to participate in the calls, when are they, and where is the most up to date information about them.

The next call is this Thursday. Logistics and agenda have been posted here:

https://github.com/privacycg/meetings/blob/master/2020/telcons/11-12-agenda.md
