### ISSUE TITLE
Join us

### ISSUE THREAD

**Issue by Sontawore** [privacycg/admin#4]
Hi,
I would like to join the team and contribute the researches. But I dont have credentials for login page at "join us" link. Could you guide to deal with this issue?

**Comment by hober** [comment]
Hi @Sontawore,

If you don't already have a W3C account, you can [request one here](https://www.w3.org/accounts/request).

**Comment by hober** [comment]
I've tried to make this easier to figure out from this repo and our website in https://github.com/privacycg/admin/commit/c9ee1f7482034c2b893355704fe4d9169e38fc4d and https://github.com/privacycg/privacycg.github.io/commit/39b62896818fb7f8d496a07ab488a6d9b9da9892
